name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t ph-prediction-image .

    # Optional: Push to Docker Hub or GitHub Container Registry
    # Uncomment below if pushing to Docker Hub (requires secrets set)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: krushna323
          password: dckr_pat_zHMTDtY8Y82FW_gLS8KdbSGoaRo

    - name: Build Docker image
      run: docker build -t krushna323/my-image:latest .

    - name: Push Docker image
      run: docker push krushna323/my-image:latest
