name: Run PH Prediction Notebook

on:
  push:
    paths:
      - '**.ipynb'
      - '**.csv'
      - '**.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Notebook
      run: python notebook_runner.py
